name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            fileName: "proxy-textures-easycabinet_linux_x64"
            file: "proxy-textures-easycabinet"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo build --release
          mv ./target/release/${{ matrix.file }} ./${{ matrix.fileName }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ matrix.fileName }}